#!/bin/sh

set -x
cmd=$(which tmux) # tmux path
session=hello_tmux   # session name

if [ -z $cmd ]; then
  echo "You need to install tmux."
  exit 1
fi

$cmd has -t $session

if [ $? != 0 ]; then
	$cmd new-session -d -s $session "ifstat"
	$cmd split-window -v "tail -f ~/work/var/php/php_errors.log"
	$cmd selectp -t 0
	$cmd split-window -h "htop"
fi
$cmd attach-session -t $session
#$cmd att -t $session

exit 0

