#!/bin/bash

set -x
cmd="/usr/bin/tmux" # tmux path
session="hello_tmux"   # session name

if [ -z $cmd ]; then
  echo "You need to install tmux."
  exit 1
fi

$cmd has -t $session

if [ $? != 0 ]; then
	$cmd new-session -d -s $session "htop"
	$cmd split-window -h "tail -f ~/work/var/php/php_errors.log"
	$cmd split-window -v -p 40 
fi
$cmd attach-session -t $session
#$cmd att -t $session

exit 0

